# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
brazilian_portuguese = Language.create(language_name: "Brazilian Portuguese", flag_image: "https://finalprojectimg.s3.amazonaws.com/brazil.png" )
czech = Language.create(language_name: "Czech", flag_image: "https://finalprojectimg.s3.amazonaws.com/the_czech_republic.jpg" )
french = Language.create(language_name: "French", flag_image: "https://finalprojectimg.s3.amazonaws.com/france.png")
german = Language.create(language_name: "German", flag_image: "https://finalprojectimg.s3.amazonaws.com/germany.png")
italian = Language.create(language_name: "Italian", flag_image: "https://finalprojectimg.s3.amazonaws.com/Italy.png")
japanese = Language.create(language_name: "Japanese", flag_image: "https://finalprojectimg.s3.amazonaws.com/japan.png")
spanish = Language.create(language_name: "Spanish", flag_image: "https://finalprojectimg.s3.amazonaws.com/spanish.png" )
turkish = Language.create(language_name: "Turkish", flag_image: "https://finalprojectimg.s3.amazonaws.com/turkey.png" )

brazilian_portuguese_1 = Phrase.create(english_phrase: "Hello", foreign_phrase: "Oi", language_id: 1)
brazilian_portuguese_2 = Phrase.create(english_phrase: "How are you?", foreign_phrase: "Como você está", language_id: 1)
brazilian_portuguese_3 = Phrase.create(english_phrase: "Yes", foreign_phrase: "Sim", language_id: 1)
brazilian_portuguese_4 = Phrase.create(english_phrase: "No'", foreign_phrase: "Não", language_id: 1)
brazilian_portuguese_5 = Phrase.create(english_phrase: "My name is ______.", foreign_phrase: "Meu nome é ______.", language_id: 1)
brazilian_portuguese_6 = Phrase.create(english_phrase: "Please", foreign_phrase: "Por favor", language_id: 1)
brazilian_portuguese_7 = Phrase.create(english_phrase: "Okay", foreign_phrase: "Está bem", language_id: 1)
brazilian_portuguese_8 = Phrase.create(english_phrase: "Excuse me", foreign_phrase: "Com licença", language_id: 1)
brazilian_portuguese_9 = Phrase.create(english_phrase: "Thank you", foreign_phrase: "Obrigado(male) - Obrigada(female)", language_id: 1)
brazilian_portuguese_10 = Phrase.create(english_phrase: "Good Night", foreign_phrase: "Boa note", language_id: 1)

czech_1 = Phrase.create(english_phrase: "Hello", foreign_phrase: "Ahoj", language_id: 2)
czech_2 = Phrase.create(english_phrase: "How are you?", foreign_phrase: "Jak se máš?", language_id: 2)
czech_3 = Phrase.create(english_phrase: "Yes", foreign_phrase: "Ano", language_id: 2)
czech_4 = Phrase.create(english_phrase: "No", foreign_phrase: "Ne", language_id: 2)
czech_5 = Phrase.create(english_phrase: "My name is ______.", foreign_phrase: "menuji se ______.", language_id: 2)
czech_6 = Phrase.create(english_phrase: "Please", foreign_phrase: "Prosím", language_id: 2)
czech_7 = Phrase.create(english_phrase: "Okay", foreign_phrase: "Dobře", language_id: 2)
czech_8 = Phrase.create(english_phrase: "Excuse me", foreign_phrase: "Promiňte", language_id: 2)
czech_9 = Phrase.create(english_phrase: "Thank you", foreign_phrase: "Děkuji", language_id: 2)
czech_10 = Phrase.create(english_phrase: "Good Night", foreign_phrase: "Dobrou noc", language_id: 2)

french_1 = Phrase.create(english_phrase: "Hello", foreign_phrase: "Bonjour", language_id: 3)
french_2 = Phrase.create(english_phrase: "How are you?", foreign_phrase: "Ça va?", language_id: 3)
french_3 = Phrase.create(english_phrase: "Yes", foreign_phrase: "Oui", language_id: 3)
french_4 = Phrase.create(english_phrase: "No", foreign_phrase: "Non", language_id: 3)
french_5 = Phrase.create(english_phrase: "My name is ______.", foreign_phrase: "Je m’apelle ______.", language_id: 3)
french_6 = Phrase.create(english_phrase: "Please", foreign_phrase: "S'il vous plait", language_id: 3)
french_7 = Phrase.create(english_phrase: "Okay", foreign_phrase: "D’accord", language_id: 3)
french_8 = Phrase.create(english_phrase: "Excuse me", foreign_phrase: "Exusez-moi", language_id: 3)
french_9 = Phrase.create(english_phrase: "Thank you", foreign_phrase: "Merci", language_id: 3)
french_10 = Phrase.create(english_phrase: "Good Night", foreign_phrase: "Bonne nuit", language_id: 3)

german_1 = Phrase.create(english_phrase: "Hello", foreign_phrase: "Hallo", language_id: 4)
german_2 = Phrase.create(english_phrase: "How are you?", foreign_phrase: "Wie geht es dir?", language_id: 4)
german_3 = Phrase.create(english_phrase: "Yes", foreign_phrase: "Ja", language_id: 4)
german_4 = Phrase.create(english_phrase: "No", foreign_phrase: "Nein", language_id: 4)
german_5 = Phrase.create(english_phrase: "My name is ______.", foreign_phrase: "Mein name ist ______.", language_id: 4)
german_6 = Phrase.create(english_phrase: "Please", foreign_phrase: "Bitte", language_id: 4)
german_7 = Phrase.create(english_phrase: "Okay", foreign_phrase: "Okay", language_id: 4)
german_8 = Phrase.create(english_phrase: "Excuse me", foreign_phrase: "entschuldigen Sie mich", language_id: 4)
german_9 = Phrase.create(english_phrase: "Thank you", foreign_phrase: "Danke", language_id: 4)
german_10 = Phrase.create(english_phrase: "Good Night", foreign_phrase: "Gute Nacht", language_id: 4)

italian_1 = Phrase.create(english_phrase: "Hello", foreign_phrase: "Ciao", language_id: 5)
italian_2 = Phrase.create(english_phrase: "How are you?", foreign_phrase: "Come stai?", language_id: 5)
italian_3 = Phrase.create(english_phrase: "Yes", foreign_phrase: "Si", language_id: 5)
italian_4 = Phrase.create(english_phrase: "No", foreign_phrase: "No", language_id: 5)
italian_5 = Phrase.create(english_phrase: "My name is ______.", foreign_phrase: "Mi chiamo ______.", language_id: 5)
italian_6 = Phrase.create(english_phrase: "Please", foreign_phrase: "Per favore", language_id: 5)
italian_7 = Phrase.create(english_phrase: "Okay", foreign_phrase: "Mi scusi", language_id: 5)
italian_8 = Phrase.create(english_phrase: "Excuse me", foreign_phrase: "Va bene", language_id: 5)
italian_9 = Phrase.create(english_phrase: "Thank you", foreign_phrase: "Grazie", language_id: 5)
italian_10 = Phrase.create(english_phrase: "Good Night", foreign_phrase: "Buona sera", language_id: 5)

japanese_1 = Phrase.create(english_phrase: "Hello!", foreign_phrase: "Onegai shimasu - お願いします", language_id: 6)
japanese_2 = Phrase.create(english_phrase: "How are you?", foreign_phrase: "お元気ですか - O-genki desu ka", language_id: 6)
japanese_3 = Phrase.create(english_phrase: "Yes", foreign_phrase: "Hai - はい", language_id: 6)
japanese_4 = Phrase.create(english_phrase: "No", foreign_phrase: "No - いいえ", language_id: 6)
japanese_5 = Phrase.create(english_phrase: "My name is ______.", foreign_phrase: "watashi no namae wa - 私の名前はジョンです", language_id: 6)
japanese_6 = Phrase.create(english_phrase: "Please", foreign_phrase: "Onegai shimasu - お願いします", language_id: 6)
japanese_7 = Phrase.create(english_phrase: "Okay", foreign_phrase: "Ha -  はい", language_id: 6)
japanese_8 = Phrase.create(english_phrase: "Excuse me", foreign_phrase: "Sumimasen - すみません", language_id: 6)
japanese_9 = Phrase.create(english_phrase: "Thank you", foreign_phrase: "Arigatō - ありがとう", language_id: 6)
japanese_10 = Phrase.create(english_phrase: "Good Night", foreign_phrase: "Oyasuminasai - おやすみなさい", language_id: 6)

spanish_1 = Phrase.create(english_phrase: "'Hello!'", foreign_phrase: "Hola", language_id: 7)
spanish_2 = Phrase.create(english_phrase: "How are you?", foreign_phrase: "Como estas?", language_id: 7)
spanish_3 = Phrase.create(english_phrase: "Yes", foreign_phrase: "Si", language_id: 7)
spanish_4 = Phrase.create(english_phrase: "No", foreign_phrase: "No", language_id: 7)
spanish_5 = Phrase.create(english_phrase: "My name is ______.", foreign_phrase: "Mi nombre es ______.", language_id: 7)
spanish_6 = Phrase.create(english_phrase: "Please", foreign_phrase: "Por favor", language_id: 7)
spanish_7= Phrase.create(english_phrase: "Okay", foreign_phrase: "Esta bien", language_id: 7)
spanish_8 = Phrase.create(english_phrase: "Excuse me", foreign_phrase: "Permiso", language_id: 7)
spanish_9 = Phrase.create(english_phrase: "Thank you", foreign_phrase: "Gracias", language_id: 7)
spanish_10 = Phrase.create(english_phrase: "Good Night", foreign_phrase: "Buenas noches", language_id: 7)

turkish_1 = Phrase.create(english_phrase: "Hello", foreign_phrase: "Merhaba", language_id: 8)
turkish_2 = Phrase.create(english_phrase: "How are you?", foreign_phrase: "Nasilsin", language_id: 8)
turkish_3 = Phrase.create(english_phrase: "Yes", foreign_phrase: "Evet", language_id: 8)
turkish_4 = Phrase.create(english_phrase: "No", foreign_phrase: "Hayir", language_id: 8)
turkish_5 = Phrase.create(english_phrase: "My name is ______.", foreign_phrase: "Benim adim ______", language_id: 8)
turkish_6 = Phrase.create(english_phrase: "Please", foreign_phrase: "Lütfen", language_id: 8)
turkish_7 = Phrase.create(english_phrase: "Okay", foreign_phrase: "Tamam", language_id: 8)
turkish_8 = Phrase.create(english_phrase: "Excuse me", foreign_phrase: "Afedersiniz", language_id: 8)
turkish_9 = Phrase.create(english_phrase: "Thank you", foreign_phrase: "Teşekkürler", language_id: 8)
turkish_10 = Phrase.create(english_phrase: "Good Night", foreign_phrase: "Iyi akşamlar", language_id: 8)